### ISSUE TITLE
History points for perturbation field in a linear simulation

### ISSUE THREAD

**Issue by akhoubani** [snek5000/snek5000#125]
We would like to write the perturbation field in the for example `cbox.his` file when `params.nek.problemtype.equation = "incompLinNS"` is activated.

**Comment by paugier** [comment]
Do you know how to do it without snek5000? I mean with a pure Nek5000 simulation.

**Comment by akhoubani** [comment]
I think I should copy the history points subroutine and paste it in `.usr.f` file, change it and include a condition in `subroutine userchk`. Then we can add some lines to `output.history_points`.

**Comment by ashwinvis** [comment]
Have a look at 

https://github.com/Nek5000/Nek5000/blob/5afb6179daf69c5f1d0e5a6eab49d6f07e0c622f/core/reader_par.f#L645-L693

**Comment by akhoubani** [comment]
`jp=0` means base flow. What we are looking for is `jp=1` which means first perturbation field. In the `subroutine hpts` could we? add lines like `call copy(wrk(1,1),vxp,ntot)` with a condition for example to
```fortran
if(ifvo) then
        call copy(wrk(1,1),vx,ntot)
        call copy(wrk(1,2),vy,ntot)
        if(if3d) call copy(wrk(1,3),vz,ntot)
        nflds = ldim
      endif
```

**Comment by akhoubani** [comment]
For example we use `subroutine outpost2(v1,v2,v3,vp,vt,nfldt,name3)` for dumping perturbation field in `userchk`.

**Comment by ashwinvis** [comment]
You could try something like that. Also you need to increase the number of fields by changing `ldimt` (`params.oper.scalars`) or by modifying `nfldm` here:

```fortran
       parameter(nfldm=ldim+ldimt+1)
```

**Comment by paugier** [comment]
I don't know enough Nek5000 to really be able to think about what should be done.

We have 2 possibilities:

1. Add another Fortran file in snek5000 with everything to dump history points for the perturbation (a copy + modifications of things in https://github.com/exabl/Nek5000/blob/stable/core/postpro.f#L1517), then we just call our own function in the .usr file.
2. Modify https://github.com/exabl/Nek5000/blob/stable/core/postpro.f#L1517 and send a PR in the main Nek5000 repository. It would be cleaner but given how our previous PR is handled https://github.com/Nek5000/Nek5000/pull/749, I'm not sure it is the way to go.

For a linear simulation, if I remember well the base flow can be steady or unsteady, isn't it? Anyway, it would be useful for history points to have the value of the base flow at the particular hist points.

So yes, we should save more numbers (corresponding to more "fields") per point in the .his file and then adapt the Python file.

**Comment by akhoubani** [comment]
> For a linear simulation, if I remember well the base flow can be steady or unsteady, isn't it? Anyway, it would be useful for history points to have the value of the base flow at the particular hist points.

If I understand well from Nek5000, there should be a base flow field to restart from. I see this `solveBaseFlow` but I couldn't manage to work with to have base flow! The result was not reasonable for me.

**Comment by akhoubani** [comment]
I realized that it is troublesome to change the internal routines of Nek5000. I define these lines in `.usr.f` file:

```fortran
call opcopy(vtmp(1,1),vtmp(1,2),vtmp(1,ndim),vx,vy,vz)
n = NX1*NY1*NZ1*NELV
call copy(ttmp,T,n)
call opcopy(vx, vy, vz, vxp, vyp, vzp)
call copy(T,TP,n)

call hpts()

call opcopy(vx,vy,vz, vtmp(1,1),vtmp(1,2),vtmp(1,ndim))
call copy(T,ttmp,n)
```
I pushed [ Add simple linear script #16 ](https://github.com/exabl/snek5000-cbox/pull/16).

**Comment by paugier** [comment]
@akhoubani could you please check if this issue can be closed? Is there still something to do?

**Comment by akhoubani** [comment]
I guess it can be closed. I managed to write perturbation pressure in history points in [NL restart scripts #16 ](https://github.com/exabl/snek5000-cbox/pull/23).

**Comment by paugier** [comment]
I close. However, it's important to remember that you need to mention in some pages of the documentation of snek5000 that there are advanced examples in snek5000-cbox documentation.
