### ISSUE TITLE
Warnings related to arrays while compiling

### ISSUE THREAD

**Issue by akhoubani** [snek5000/snek5000#130]
As you may know, we receive a lot of warnings related to arrays in different routines while compiling `snek-cbox`. 

I noticed if we use the last commit of the main branch of `Nek5000`, we don't get those warnings.

**Comment by ashwinvis** [comment]
Good to know. When they publish a stable release we can change to it.

As you may already know, with snek5000, you can always change to different Nek5000 version by setting the NEK_SOURCE_ROOT environment variable.

I don't think there is much to do from our end is it?

**Comment by ashwinvis** [comment]
I had a custom makefile _usr template and a custom write_makefile_usr method in my old project which suppresses a lot of errors and restricts to user code. I can add this to snek5000.

**Comment by akhoubani** [comment]
> Good to know. When they publish a stable release we can change to it.

Great.

> 
> As you may already know, with snek5000, you can always change to different Nek5000 version by setting the NEK_SOURCE_ROOT environment variable.

Yes, I'm aware of it.

> 
> I don't think there is much to do from our end is it?

Just wanted to have it in mind. Thanks.

**Comment by ashwinvis** [comment]
Closed in #145
