### ISSUE TITLE
More than 10 USERPARAMS in Nek5000

### ISSUE THREAD

**Issue by akhoubani** [snek5000/snek5000#131]
We need more than 10 user parameters in the `.par` file. I changed [`PARDICT`](https://github.com/exabl/Nek5000/blob/140c4fd96c28df5f4d415e89be57424a7eba3691/core/PARDICT) file to have 20 user parameters for the moment.

I am not sure how to include it in snek5000. Should I have a pull request here? I wonder if you could guide me. Thanks.

**Comment by ashwinvis** [comment]
PRs welcome! I could not come up with a clean solution for this right now. The check is done here:

https://github.com/snek5000/snek5000/blob/2c914047fdb5679c5345cb83856e785e780a9b93/src/snek5000/params.py#L54

https://github.com/snek5000/snek5000/blob/2c914047fdb5679c5345cb83856e785e780a9b93/src/snek5000/params.py#L176

You can add a keyword argument for the method, something like:

```py
    def __update_par_section(
        self, ..., check_user_params_index=True
    ):
      ...
          if  check_user_params_index: _check_user_param_index(idx_uparam)
      ...

```

which make this check optional. But how would one make this a public API?

For the time being you can [mock](https://docs.python.org/3/library/unittest.mock.html) or monkey-patch the `_check_user_param_index` function. Have a look at this presentation if you don't know how:

https://pganssle-talks.github.io/pycon-us-2022-upstream-bugs/#/

**Comment by ashwinvis** [comment]
The fork is now transferred to

https://github.com/snek5000/Nek5000

There are no open PRs, but the `stable` branch must be rebased to upstream v19 and the compilation race patch must be cherry picked.

**Comment by akhoubani** [comment]
It is based on the fork that we have in `lib` directory of `snek5000`.

**Comment by paugier** [comment]
What is the status of this problem?

What are the differences between our version of Nek5000 (https://github.com/snek5000/Nek5000) and the official Nek5000 repository?

Is there a PR on Nek5000 to include our fix to be able to use more than 10 user params? What is this fix (link commit / PR)?

**Comment by paugier** [comment]
@akhoubani did you create a PR on Nek5000 repo? Could you please mention it here?

**Comment by paugier** [comment]
@akhoubani ???

**Comment by akhoubani** [comment]
I opened a pull request. You can see it [here](https://github.com/Nek5000/Nek5000/pull/778).

**Comment by paugier** [comment]
Your PR has been accepted in NEK5000! Nice!

We just need to remove the warning in `_check_user_param_index` and this issue can be closed!

**Comment by paugier** [comment]
Oh what about our fork https://github.com/snek5000/Nek5000 ? Related to https://github.com/snek5000/snek5000/issues/174 (link between our Nek5000 and upstream...).
