### ISSUE TITLE
After 0.8.0 release: publish in Zenodo

### ISSUE THREAD

**Issue by ashwinvis** [snek5000/snek5000#132]
I have made a draft, in Zenodo Sandbox here:

https://sandbox.zenodo.org/record/1061434

Take a look and let me know if any modifications are required. This would make the software citeable.

**Comment by ashwinvis** [comment]
@akhoubani and @paugier Did you check if your affiliations are correct in https://sandbox.zenodo.org/record/1061434?

**Comment by akhoubani** [comment]
> @akhoubani and @paugier Did you check if your affiliations are correct in https://sandbox.zenodo.org/record/1061434?

Yes, it is correct. Thanks.

**Comment by paugier** [comment]
0.8.0rc1 has been released on PyPI: https://pypi.org/project/snek5000/0.8.0rc1/

The zenodo badge is now in the README.
