### ISSUE TITLE
Saving (and plot) of an estimation of remaining_clock_time

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#137]
From my experience, the figure obtained in fluidsim with `sim.output.print_stdout.plot_clock_times()` is VERY useful.

The related code is in https://foss.heptapod.net/fluiddyn/fluidsim/-/blob/branch/default/fluidsim/base/output/print_stdout.py (methods `_evaluate_duration_left` and of course `plot_clock_times`).

The logic of these methods should also applies for Nek5000.

So we could move some code in `fluidsim_core` and use it for snek.

Note that we don't need to write that for each time step and we don't need to write that in stdout (it can be another file with for some time steps `it, time, dt, remaining_clock_time`).

Related to #81 and #121

**Comment by ashwinvis** [comment]
Also this detail while deciding end of sim: https://github.com/snek5000/snek5000/pull/121#issuecomment-995789318

**Comment by paugier** [comment]
@ashwinvis it would be great if you could work on the Fortran/Nek5000 part of this one (because I would struggle to do it :-)). Then, I will be able to work on the Python/fluidsim-core part.

It seems to me that 

- It can first be implemented in our tgv solver.
- We can use some `remaining-clock-time.csv` files in the session directories.
- A reasonable condition to print a new line in these files could be based on the real clock time, for example every 10 s, and I tend to think that we don't really need a user parameter for this (?).

**Comment by paugier** [comment]
I'm going to work on this one so that @ashwinvis you can focus on #179!

**Comment by ashwinvis** [comment]
Thank you for working on this... I am still on vacation. Will be back around 11/1
