### ISSUE TITLE
Fix the build on readthedocs

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#144]
> @ashwinvis do you think it could be possible to run these simulations on RTD servers? With conda, we should be able to install gfortran so I guess it could work.

We can try. You will have to add `snek5000-cbox` at the stable branch in `docs/requirements.txt`. Btw, have you updated the stable branch?

_Originally posted by @ashwinvis in https://github.com/snek5000/snek5000/issues/141#issuecomment-1286887973_

**Comment by paugier** [comment]
@ashwinvis I guess it would me more efficient if you work on this one. I suspect that we will need to use conda/mamba to get a Fortran compiler on RTD... See https://docs.readthedocs.io/en/stable/guides/conda.html

**Comment by ashwinvis** [comment]
I added the Github -> rtd webhook. That was missing.

**Comment by paugier** [comment]
So the build on RTD passes but there is (as expected) an error in the notebook :

https://snek5000.readthedocs.io/en/latest/tuto_simul_cbox.html

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [1], line 3
      1 import numpy as np
----> 3 from snek5000_cbox.solver import Simul
      5 params = Simul.create_default_params()
      7 aspect_ratio = params.oper.aspect_ratio = 1.0

ModuleNotFoundError: No module named 'snek5000_cbox'
```

**Comment by paugier** [comment]
Related : we should also update https://snek5000.readthedocs.io/en/latest/install.html#install-using-conda-mamba

One needs a Fortran compiler!

**Comment by ashwinvis** [comment]
Done in #157
