### ISSUE TITLE
sim.output.spatial_means

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#150]
Reading the .usr file of tvg, I see that it would be useful/easy to have a generic `sim.output.spatial_means`.

It seems to me that it would be better to save this data in another text file than the .log file.

Methods like `spatial_means.load` (getting a pandas dataframe) and `spatial_means.plot` would be useful.

- We would need another user params...
- The code for the condition in tgv.usr should be improved to have a condition in time unit (and not time iteration).

I don't include this for 0.8.0 but after #137, this should be very easy.

- [ ] Add How to save/load/plot spatial means data.

**Comment by paugier** [comment]
@akhoubani Could you please work on the tgv.usr to save every 0.2 time units ? Now it is every 50 time steps which is bad.

**Comment by akhoubani** [comment]
> @akhoubani Could you please work on the tgv.usr to save every 0.2 time units ? Now it is every 50 time steps which is bad.

Yes, I'll do it.
