### ISSUE TITLE
Include a movie in README

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#156]
We could also include a movie when that PR is finalized. I think if drag and drop from Github's readme editor, we get a link to embed, we dont need to commit the file in git.

https://github.blog/2021-05-13-video-uploads-available-github/

_Originally posted by @ashwinvis in https://github.com/snek5000/snek5000/pull/154#pullrequestreview-1160958483_

**Comment by paugier** [comment]
I wonder if we can get a nice movie (with a bit of small scales) from a phill simulation at moderately high resolution? We can also choose cbox, which produces nice flows in terms of representation at moderately high Ra.

Anyway, we should have a script which produces the movie (docs/scripts/simul_phill_movie.py if we choose phill).

**Comment by ashwinvis** [comment]
I think a cbox movie will be more visually appealing and quick to run. We can have a code snippet for a phill movie to show how to do it in 3D, but dont need to show it.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by paugier** [comment]
@akhoubani could you please create a script docs/examples/scripts/simul_cbox_movie.py which

1. runs a ~10 min cbox simulation designed to make nice images (may be just start from rest at moderate Ra?)
2. produces a nice movie (.gif) with `sim.output.animate`

**Comment by paugier** [comment]
Needs https://github.com/snek5000/snek5000-cbox/issues/41

**Comment by paugier** [comment]
Done in https://github.com/snek5000/snek5000/pull/201
