### ISSUE TITLE
Improve cbox tutorial with check from Python + larger Ra / smaller t_end

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#167]
cbox tutorial simulation (https://github.com/snek5000/snek5000/blob/main/docs/examples/scripts/tuto_cbox.py) should be improved to demonstrate what is done in https://github.com/snek5000/snek5000-cbox/blob/main/doc/examples/nonlinear_from_rest/run_simul_check_from_python.py (but it should stay much simpler! without arguments in particular).

Also Ra can be increased a bit to get a larger/faster exponential increase.

With the check process, t_end will be smaller (so the simulation should be smaller).

**Comment by paugier** [comment]
Unfortunately, our cbox tutorial (https://snek5000.readthedocs.io/en/latest/tuto_cbox.html) is a bit broken. The simulation is not as good as "before" (using "" because I don't know when exactly it broke).

This can be seen in the history point plots where we see random noise for t > 200 and no exponential increase... @akhoubani could you please investigate this problem with the script docs/examples/scripts/tuto_cbox.py ?

**Comment by akhoubani** [comment]
I checked it. I guess it is because of the coarse grid and large target CFL. I decreased a bit CFL and end time in #177.

**Comment by paugier** [comment]
#199 and https://github.com/snek5000/snek5000-cbox/pull/37 improves the situation. 

Our tutorial is again fine.
