### ISSUE TITLE
snek5000/Nek5000 rebased on upstream?

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#174]
We have an issue with our Nek5000 version. At the same time we need to follow upstream (https://github.com/Nek5000/Nek5000) and we also need few changes not (yet) in upstream.

It would be nice to easily be able to get the differences between what we use and upstream and to have a simple process to use something based on upstream master.

See https://github.com/Nek5000/Nek5000/pull/778

**Comment by ashwinvis** [comment]
We can remove the current repository `snek5000/Nek5000` repo and depend on a plain fork (so it is easy to compare changes) with 
- a `master` branch which is in sync with upstream
- a `stable` branch which is in sync with upstream upto the last release
- a `develop` branch which is `stable` +  the changes that we need backported using `git cherry-pick` or something similar.

**Comment by paugier** [comment]
I think this would be the proper solution. But are we going to loose something important when we remove the current repo `snek5000/Nek5000`?

**Comment by paugier** [comment]
We can move `snek5000/Nek5000` to `snek5000/Nek5000-old-fork` and then properly fork `Nek5000/Nek5000`.

I guess it would be then safer to reclone snek5000 repo locally on our computers.

And finally fix what needs to be fixed.

**Comment by ashwinvis** [comment]
Yes. Sounds good.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by paugier** [comment]
This is already done and we now use snek5000/Nek5000.
