### ISSUE TITLE
After 0.8.0 release: communicate to the Nek5000 and fluid mechanics communities

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#176]
After the 0.8.0 release, we need to communicate about Snek5000. The potential feedback could be used to build 0.9.0. Our software paper should be based on 0.9.0.

**Comment by ashwinvis** [comment]
Were you able to do this? I think https://groups.google.com/g/nek5000 is the best place to reach out. I hope they won't mind having such a conversation there.

**Comment by paugier** [comment]
I sent emails to lists of researchers in France.

I need to join the google group to send an email in https://groups.google.com/g/nek5000. I sent a request for that.

Some messages need to be sent from the Fluiddyn Mastodon/Twitter accounts...

**Comment by paugier** [comment]
A message has been sent to the Nek5000 user group https://groups.google.com/g/nek5000/c/URtEh8DKrzs. Finally, the 0.8.0 milestone is reached!

**Comment by paugier** [comment]
Thank you @ashwinvis  and @akhoubani for your effort. Next step is [0.9.0](https://github.com/snek5000/snek5000/milestone/2) and a JOSS paper. The amount of work for this target is now very reasonable.
