### ISSUE TITLE
Nek5000 libraries rebuild in case of compiler change is not triggered

### ISSUE THREAD

**Issue by ashwinvis** [snek5000/snek5000#179]
Sometimes a manual edit of the nek5000_make_config.yml is required to rebuild Nek5000
```py
~/Sources/snek5000/snek5000/lib/Nek5000 @140c4fd9* 10s
snek ❯ snakemake --configfile nek5000_make_config.yml -j1 --snakefile ../../src/snek5000/resources/nek5000.smk  3rd_party/gslib/lib/libgs.a 3rd_party/blasLapack/libblasLapack.a
```

**Comment by paugier** [comment]
Just a question: do we really need that for 0.8.0 ? Could we postpone this issue to 0.9.0 ?

**Comment by ashwinvis** [comment]
Okay it is not that crucial anyway

**Comment by paugier** [comment]
Just need to improve https://snek5000.readthedocs.io/en/latest/how-to/rebuild-nek.html
