### ISSUE TITLE
Format of params.oper.Lx in tgv.box

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#189]
Lx is encoded with only 4 digits after point in tgv.box. For example for `params.oper.Lx = 2 * pi`, this gives

```
0.0000 6.2832 1.0000                      x0 x1 ratio
```

This is really very inaccurate. Does genbox support more digits than that?

**Comment by ashwinvis** [comment]
No genbox is like that. The way to get more precision is to assign 1.0 as lengths and deform the mesh in usrdat2 as done in phill example.

**Comment by paugier** [comment]
Wha... It surprising how Nek5000 can be bad in some aspects.

Just need to add a comment in box.j2 (I will do that) and we can close.
