### ISSUE TITLE
Command snek-make ?

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#193]
Directly using snakemake is kind of difficult. The help given by `snakemake -h` is very long and not very useful for a snek5000 user.

It would make sense to have our own command to launch snakemake targets.

For example `snek-make` and `snek-make -h` could provide a short and useful help (with the list of targets).

`snek-make -np 2 run` and `snek-make -np 2 run_fg` would launch the simulation...

What do you think @ashwinvis and @akhoubani ?

**Comment by ashwinvis** [comment]
Ok, as long as it is simple.

If it is not too mumch work. It might be useful to also have

- list
- dryrun
- dag (extended with a graphviz dot call)

options from the snakemake CLI.
