### ISSUE TITLE
Command snek-ipy-load

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#194]
It would be nice to have a command snek-ipy-load that does the equivalent of

```
ipython --matplotlib -i -c 'from snek5000 import load; slm = load(); params = sim.params"
```

Note that I don't know how it can be done.

**Comment by ashwinvis** [comment]
Shouldn't it be better to define a `%snek_load` IPython magic? As of now a `%snek` magic exists to initialize a new simulation.

**Comment by ashwinvis** [comment]
https://github.com/snek5000/snek5000/blob/main/src/snek5000/magic.py

**Comment by ashwinvis** [comment]
And this seems to be the way to make such a command:

https://ipython.readthedocs.io/en/stable/config/intro.html#running-ipython-from-python

**Comment by paugier** [comment]
2 commands which work:

```
python -c 'from IPython import start_ipython; start_ipython(argv=["--matplotlib", "-i", "-c", "from fluidsim import load; sim = load()"])'

python -c 'from IPython import start_ipython; start_ipython(argv=["--matplotlib"], user_ns={"a": 1})'
```

I'm going to try to add this command now. It should be simple actually.
