### ISSUE TITLE
Rename snek commands

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#195]
We will have a set of commands. 

- snek5000-info
- snek5000-config-init
- snek-ipy-load
- snek-make
- snek-restart
- ...

It is the good time to find good names for them. For example, I wonder if the 5000 is very useful. 

- snek5000-info could be renamed  snek-info
- snek5000-config-init could be renamed snek-generate-config

@ashwinvis @akhoubani what would you prefer?

**Comment by ashwinvis** [comment]
Shorter is better. +1 for snek-

-------- Original Message --------

**Comment by akhoubani** [comment]
I agree with you.
