### ISSUE TITLE
Template inheritance, add blocks for users to extend

### ISSUE THREAD

**Issue by ashwinvis** [snek5000/snek5000#200]
Good idea on template inheritance. If I understood the docs, it needs upstream support with a block defined as.

```jinja
{% block user_size %} 
{% endblock %}
```

Other templates can also have such blocks to allow reusability.

_Originally posted by @ashwinvis in https://github.com/snek5000/snek5000-cbox/issues/35#issuecomment-1315311016_

**Comment by paugier** [comment]
Closed by https://github.com/snek5000/snek5000/pull/244 and https://github.com/snek5000/snek5000/pull/253
