### ISSUE TITLE
Create a template for creating a snek5000 package from a Nek5000 case

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#26]
As far as I understand, using snek5000 for something else than `phill` requires creating a new package similar to `phill`, which is quite difficult.

It would be really nice to have a tool to do that automatically from Nek5000 files (something like https://github.com/paugier/nek5000-convection-box).

Note that I can invest a bit of time on that but I'd like to have your point of view.

**Comment by ashwinvis** [comment]
I think that would be really nice to have. I can create a repo and we can work together on that cookiecutter.

One thing I would like to have before the cookiecutter is to move most of the [Snakemake rules as a module](https://snakemake.readthedocs.io/en/stable/snakefiles/modularization.html?highlight=module#modules) in the main `snek5000` repo. This requires trying out `snakemake >= 6.0.0`. This would reduce the amount of boilerplate involved.

**Comment by ashwinvis** [comment]
Ref. #22

**Comment by ashwinvis** [comment]
Created an empty repository: https://github.com/exabl/cookiecutter-snek5000

**Comment by paugier** [comment]
Nice! I'm going to wait for #22!

**Comment by paugier** [comment]
The first step would be to split docs/packaging.rst to have the `snek5000_canonical` project inside the doc.

**Comment by ashwinvis** [comment]
Working on porting `snek5000_canonical` into a reusable template which relies on `copier` (modern alternative to cookiecutter)

https://copier.readthedocs.io
