### ISSUE TITLE
Release snek5000 0.9.0

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#267]
- [x] release tgv solver 0.2.0
- [x] release box solver 0.2.0
- [x] release phill solver 0.5.0
- [x] release snek5000 0.9.0
- [x] email NEK5000 mailing list
- [ ] Mastodon / tweeter (@ashwinvis)
- [x] email to NEK5000 users we know

**Comment by paugier** [comment]
See https://groups.google.com/g/nek5000/c/6aA_lQY53RA

@ashwinvis if you can send a short message with the fluidsim account that would be great and we would be able to close this issue.

**Comment by ashwinvis** [comment]
Done https://pythondevs.social/notice/ARo2wMU3O0WTiOuiO0 it should be crossposted to Twitter in a while.

**Comment by ashwinvis** [comment]
Yes, there it is https://nitter.snopyta.org/pyfluiddyn/status/1616108197248466945#m
