### ISSUE TITLE
Phill example: Runtime error due to USERPARAM12

### ISSUE THREAD

**Issue by joneuhauser** [snek5000/snek5000#294]
Attempting to run the example in the README, everything works fine until and including compilation. However, I get (using stock nek5000, v19.0)

 Reading ./session_00/phill.par                                                                                                              
 ERROR: Par file contains unknown key GENERAL:USERPARAM12  

Looking at the values, they might come from 

```
    <history_points coords="None" write_interval="100"/>  

    <remaining_clock_time period_save_in_seconds="5.0"/>  
```

In v19.0, only 10 user params were allowed: https://github.com/Nek5000/Nek5000/blob/v19.0/core/PARDICT

It works fine using current master, but 19.0 is the last stable version.

**Comment by ashwinvis** [comment]
It comes from remaining_clock_time feature

https://github.com/snek5000/snek5000/blob/7278d405118b2f366eefb28cce6d7b0bc244ef9f/src/snek5000/output/remaining_clock_time.py#L13C10-L13C10

> In v19.0, only 10 user params were allowed

That is correct. Initially the idea was to build snek5000 to handle the latest stable version of Nek5000 alone. However we,

1. discovered a bug in v19 which can cause simultaneously launched simulation to fail: https://github.com/snek5000/Nek5000/commit/3e538555256b047a6d534111efa669e0557d0979, and
2. required more user parameters for the sake of snek5000-cbox (#131) which was implemented in Nek5000's master branch (https://github.com/Nek5000/Nek5000/commit/5581603ce76cbf54d9b8a5e73b6044a7ba8678dd)

at which point we don't exactly support the stable version. I think the best option for us is to change the wording that it is based on v19. What do you think @paugier?

**Comment by paugier** [comment]
It is indeed a complicated problem. v19 is enough buggy that it can't be used with all Snek5000 solvers. Unfortunately, there is no more recent official releases including our fixes.  Note that v19 has been release in late 2019. I don't know if Nek5000 developers plan to finally release a new stable version.

And now https://github.com/Nek5000/Nek5000 master deeply changed some behavior without any explanation (see https://github.com/Nek5000/Nek5000/issues/792 and https://github.com/snek5000/snek5000/issues/270) and we can't use it anymore.

So currently Snek5000 users actually need to use our own Nek5000 fork (https://github.com/snek5000/Nek5000) as we do in our CI.

Therefore, we need to mention our fork in our documentation (in the README and the installation page I guess).

@ashwinvis would you be brave enough to add few words about our fork (and maybe about this problem) in our documentation?
