### ISSUE TITLE
Readme: error on history_points.plot()

### ISSUE THREAD

**Issue by joneuhauser** [snek5000/snek5000#296]
To quote:

> A simulation directory is created automatically (with this example, something like ~/Sim_data/examples_snek_phill/phill_readme_12x10x8_V1.x1.x1._2022-10-27_15-21-58). Then, the simulation object can be recreated from this directory. An easy way would be to go into this directory, start IPython with the snek-ipy-load command, and run:
>... 
>sim.output.history_points.plot()

This fails because the phill solver doesn't define history points. Two fixes:

1) Fail more gracefully (raise an Error before returning in history.pints:31)
2) Don't imply in the readme that these post processing commands refer to phill.

**Comment by paugier** [comment]
Fixed by https://github.com/snek5000/snek5000/pull/298
