### ISSUE TITLE
Quickstart phill example fails with Nek500 v19

### ISSUE THREAD

**Issue by maxhutch** [snek5000/snek5000#302]
When running the phill example with Nek5000 v19 (which is the version downloadable from the official site [here](https://nek5000.mcs.anl.gov/)), the following error is reported:
```
/----------------------------------------------------------\\
|      _   __ ______ __ __  ______  ____   ____   ____     |
|     / | / // ____// //_/ / ____/ / __ \\/ __ \\/ __ \\   |
|    /  |/ // __/  / ,<   /___ \\ / / / // / / // / / /    |
|   / /|  // /___ / /| | ____/ / / /_/ // /_/ // /_/ /     |
|  /_/ |_//_____//_/ |_|/_____/  \\___/ \\___/ \\___/      |
|                                                          |
|----------------------------------------------------------|
|                                                          |
| COPYRIGHT (c) 2008-2019 UCHICAGO ARGONNE, LLC            |
| Version:  19.0                                           |
| Web:      https://nek5000.mcs.anl.gov                    |
|                                                          |
\\----------------------------------------------------------/

 Number of MPI ranks :           8
  
 Reading ./session_00/phill.par                                                                                                              
 ERROR: Par file contains unknown key GENERAL:USERPARAM12                                                                                                                 
  
an error occured: dying ...
```

Running with the main version on github, [this version at the time of writing](https://github.com/Nek5000/Nek5000/tree/11e94661faa8991b5c6e6711daf89d1cf1aa3ed5), it does work, so this may be an implicit version dependency.

**Comment by ashwinvis** [comment]
@maxhutch yes, that's correct. We used to support v19, but now we need a more recent version containing some enhancements and bugfixes (but not the master version). See the thread in #294 and the changes we did in #299.

**Comment by paugier** [comment]
Thanks @maxhutch for filling this issue. As @ashwinvis wrote, we already have some notes in the documentation mentioning this known incompatibility. In #304, I added a line in the README to mention these notes. I hope it's going to be clearer like that.
