### ISSUE TITLE
Rename `assets`

### ISSUE THREAD

**Issue by ashwinvis** [snek5000/snek5000#31]
Find a better name for subpackage `assets` and function `get_asset`.

**Comment by paugier** [comment]
Could we use just "resources" and `get_resource` (as `importlib.resources`)? At least for me the name "resource" make more sense than `asset`. But actually "asset" would also be fine.

**Comment by ashwinvis** [comment]
`snek_resources` / `get_snek_resource`

**Comment by ashwinvis** [comment]
`sim_resources` / `get_sim_resource`

**Comment by ashwinvis** [comment]
@paugier and @akhoubani which do you like?
