### ISSUE TITLE
Logging issue: messages repeated twice

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#38]
When I run https://github.com/exabl/snek5000-cbox/blob/main/doc/examples/run_sim.py, messages are repeated twice: once in color and then again but with the words "WARNING: " or "ERROR: " prepend.

**Comment by ashwinvis** [comment]
#36 (merged) replaces the logger module. See if this helps.

**Comment by paugier** [comment]
Nop, it does not help :slightly_frowning_face:

**Comment by paugier** [comment]
I've just understood that it's related to the fact that I run 2 commands in the same scripts (`sim.make.list()` and `sim.make.exec()`)

**Comment by paugier** [comment]
We have the repetitions for all tutorials in the doc so I reopen.

**Comment by paugier** [comment]
Actually #182 did not really fix this (and it should be reverted). The issue seems to come from pymech (see https://github.com/eX-Mech/pymech/pull/67).
