### ISSUE TITLE
General doc improvements for 0.8.0 (README and first pages) 

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#92]
I find the README and the first pages of the documentation to be a bit too modest. Snek5000 is a great addition to Nek5000 and this should be clear very early when one read the README/documentation.

The README should quickly show the different aspects of the power of Snek5000, not only launching a simple simulation.

We should of course mention the different solvers already built with Snek5000 (phill, cbox, abl), with maybe nice GIF.

- [ ] better README
- [ ] better index https://snek5000.readthedocs.io
- [ ] better first tutorial page https://snek5000.readthedocs.io/en/latest/tutorials.html

**Comment by paugier** [comment]
The relation between snek5000 and Pymech should be mentioned. When pymech and pymech's API is mentioned, it should be with links.

**Comment by ashwinvis** [comment]
## Elevator Pitch

### What Snek5000 is

- Workflow manager
- Python frontend
- Framework for making a unified package for Nek5000 Fortran user code and Python utilities
- Thin wrapper
- Powered by progress made Python packages such as Snakemake, FluidSim, Jinja, Pytest, Xarray etc.

### What Snek5000 is not

- Rewrite of Nek5000
- Interface to Nek5000 core library (at least not until we know what future of Nek5000 looks like. See #114 )
- Monolithic

## Advantages of using Snek5000

In short, it fills in the gaps of Nek5000 user experience

- User friendly, modular, object oriented API
- Generates SIZE, par and box files from Jinja templates
- Records metadata related to the simulation into human and machine readable files (`params_simul.xml`, `config_simul.yml`)
- Out of source builds, per run
- Reuse of code (inheritance)
- Reproducible workflows, not susceptible to changes in environment variables by default
- Sensible names and defaults for the parameters
- Some parameters are automatically set as Python properties
- Get started without studying the whole documentation
- Scriptable simulation execution allowing parametric studies
- Easy to load simulation for performing offline post-processing and restarting the simulation

**Comment by ashwinvis** [comment]
Possibly more, let me know how you feel.
